11-13 16:39:43 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "NEWS" not found; SQL statement:
  drop   table   News [42102-169]
11-19 10:10:48 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "PERSON" not found; SQL statement:
INSERT INTO PERSON (AGE,PERSON_ID,PERSON_NAME) VALUES (?,?,?) [42102-169]
11-19 10:18:15 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "PERSON" not found; SQL statement:
INSERT INTO PERSON (AGE,PERSON_ID,PERSON_NAME) VALUES (?,?,?) [42102-169]
11-19 10:22:54 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Column "title" not found [42122-169]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:2893)
	at org.h2.jdbc.JdbcResultSet.get(JdbcResultSet.java:2979)
	at org.h2.jdbc.JdbcResultSet.getString(JdbcResultSet.java:291)
	at com.propn.golf.dao.ds.H2.main(H2.java:53)
11-19 10:23:14 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "PERSON" already exists; SQL statement:
  create   table   PERSON(PERSON_ID varchar(10), PERSON_NAME varchar(64),AGE number) [42101-169]
11-19 10:23:26 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "BASEENTITY" already exists; SQL statement:
CREATE TABLE BaseEntity( id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,url VARCHAR(100),  site VARCHAR(50), pubDate TIMESTAMP(8), inDate TIMESTAMP(8) ) [42101-169]
11-20 21:58:47 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: Timeout trying to lock table ; SQL statement:
UPDATE PERSON SET AGE=?,PERSON_ID=?,PERSON_NAME=? WHERE PERSON_ID=?  [50200-169]
11-20 22:02:29 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Timeout trying to lock table ; SQL statement:
UPDATE PERSON SET AGE=?,PERSON_ID=?,PERSON_NAME=? WHERE PERSON_ID=?  [50200-169]
11-20 22:02:43 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Timeout trying to lock table ; SQL statement:
UPDATE PERSON SET AGE=?,PERSON_ID=?,PERSON_NAME=? WHERE PERSON_ID=?  [50200-169]
11-20 22:02:58 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Timeout trying to lock table ; SQL statement:
UPDATE PERSON SET AGE=?,PERSON_ID=?,PERSON_NAME=? WHERE PERSON_ID=?  [50200-169]
11-21 23:25:19 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Savepoint is invalid: "SYSTEM_SAVEPOINT_0"; SQL statement:
ROLLBACK TO SAVEPOINT SYSTEM_SAVEPOINT_0 [90063-169]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.engine.Session.rollbackToSavepoint(Session.java:769)
	at org.h2.command.dml.TransactionCommand.update(TransactionCommand.java:59)
	at org.h2.command.CommandContainer.update(CommandContainer.java:75)
	at org.h2.command.Command.executeUpdate(Command.java:230)
	at org.h2.jdbc.JdbcSavepoint.rollback(JdbcSavepoint.java:66)
	at org.h2.jdbc.JdbcConnection.rollback(JdbcConnection.java:966)
	at com.jolbox.bonecp.ConnectionHandle.rollback(ConnectionHandle.java:1054)
	at com.propn.golf.dao.trans.ConnUtils.rollback(ConnUtils.java:233)
	at com.propn.golf.dao.trans.Trans.call(Trans.java:92)
	at com.propn.golf.dao.trans.TransTest$1.call(TransTest.java:30)
	at com.propn.golf.dao.trans.Trans.call(Trans.java:64)
	at com.propn.golf.dao.trans.Trans.call(Trans.java:31)
	at com.propn.golf.dao.trans.TransTest.main(TransTest.java:19)
11-21 23:25:19 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-169]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1389)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1364)
	at org.h2.jdbc.JdbcDatabaseMetaData.checkClosed(JdbcDatabaseMetaData.java:2781)
	at org.h2.jdbc.JdbcDatabaseMetaData.getTables(JdbcDatabaseMetaData.java:135)
	at com.jolbox.bonecp.BoneCP.isConnectionHandleAlive(BoneCP.java:677)
	at com.jolbox.bonecp.BoneCP.internalReleaseConnection(BoneCP.java:620)
	at com.jolbox.bonecp.ConnectionReleaseHelperThread.run(ConnectionReleaseHelperThread.java:77)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:662)
11-21 23:25:49 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Savepoint is invalid: "SYSTEM_SAVEPOINT_0"; SQL statement:
ROLLBACK TO SAVEPOINT SYSTEM_SAVEPOINT_0 [90063-169]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.engine.Session.rollbackToSavepoint(Session.java:769)
	at org.h2.command.dml.TransactionCommand.update(TransactionCommand.java:59)
	at org.h2.command.CommandContainer.update(CommandContainer.java:75)
	at org.h2.command.Command.executeUpdate(Command.java:230)
	at org.h2.jdbc.JdbcSavepoint.rollback(JdbcSavepoint.java:66)
	at org.h2.jdbc.JdbcConnection.rollback(JdbcConnection.java:966)
	at com.jolbox.bonecp.ConnectionHandle.rollback(ConnectionHandle.java:1054)
	at com.propn.golf.dao.trans.ConnUtils.rollback(ConnUtils.java:233)
	at com.propn.golf.dao.trans.Trans.call(Trans.java:92)
	at com.propn.golf.dao.trans.TransTest$1.call(TransTest.java:30)
	at com.propn.golf.dao.trans.Trans.call(Trans.java:64)
	at com.propn.golf.dao.trans.Trans.call(Trans.java:31)
	at com.propn.golf.dao.trans.TransTest.main(TransTest.java:19)
11-21 23:25:49 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-169]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1389)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1364)
	at org.h2.jdbc.JdbcDatabaseMetaData.checkClosed(JdbcDatabaseMetaData.java:2781)
	at org.h2.jdbc.JdbcDatabaseMetaData.getTables(JdbcDatabaseMetaData.java:135)
	at com.jolbox.bonecp.BoneCP.isConnectionHandleAlive(BoneCP.java:677)
	at com.jolbox.bonecp.BoneCP.internalReleaseConnection(BoneCP.java:620)
	at com.jolbox.bonecp.ConnectionReleaseHelperThread.run(ConnectionReleaseHelperThread.java:77)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:662)
11-21 23:27:32 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Savepoint is invalid: "SYSTEM_SAVEPOINT_0"; SQL statement:
ROLLBACK TO SAVEPOINT SYSTEM_SAVEPOINT_0 [90063-169]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.engine.Session.rollbackToSavepoint(Session.java:769)
	at org.h2.command.dml.TransactionCommand.update(TransactionCommand.java:59)
	at org.h2.command.CommandContainer.update(CommandContainer.java:75)
	at org.h2.command.Command.executeUpdate(Command.java:230)
	at org.h2.jdbc.JdbcSavepoint.rollback(JdbcSavepoint.java:66)
	at org.h2.jdbc.JdbcConnection.rollback(JdbcConnection.java:966)
	at com.jolbox.bonecp.ConnectionHandle.rollback(ConnectionHandle.java:1054)
	at com.propn.golf.dao.trans.ConnUtils.rollback(ConnUtils.java:233)
	at com.propn.golf.dao.trans.Trans.call(Trans.java:92)
	at com.propn.golf.dao.trans.TransTest$1.call(TransTest.java:30)
	at com.propn.golf.dao.trans.Trans.call(Trans.java:64)
	at com.propn.golf.dao.trans.Trans.call(Trans.java:31)
	at com.propn.golf.dao.trans.TransTest.main(TransTest.java:19)
11-21 23:27:32 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-169]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1389)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1364)
	at org.h2.jdbc.JdbcDatabaseMetaData.checkClosed(JdbcDatabaseMetaData.java:2781)
	at org.h2.jdbc.JdbcDatabaseMetaData.getTables(JdbcDatabaseMetaData.java:135)
	at com.jolbox.bonecp.BoneCP.isConnectionHandleAlive(BoneCP.java:677)
	at com.jolbox.bonecp.BoneCP.internalReleaseConnection(BoneCP.java:620)
	at com.jolbox.bonecp.ConnectionReleaseHelperThread.run(ConnectionReleaseHelperThread.java:77)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:662)
11-21 23:28:31 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Savepoint is invalid: "SYSTEM_SAVEPOINT_0"; SQL statement:
ROLLBACK TO SAVEPOINT SYSTEM_SAVEPOINT_0 [90063-169]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.engine.Session.rollbackToSavepoint(Session.java:769)
	at org.h2.command.dml.TransactionCommand.update(TransactionCommand.java:59)
	at org.h2.command.CommandContainer.update(CommandContainer.java:75)
	at org.h2.command.Command.executeUpdate(Command.java:230)
	at org.h2.jdbc.JdbcSavepoint.rollback(JdbcSavepoint.java:66)
	at org.h2.jdbc.JdbcConnection.rollback(JdbcConnection.java:966)
	at com.jolbox.bonecp.ConnectionHandle.rollback(ConnectionHandle.java:1054)
	at com.propn.golf.dao.trans.ConnUtils.rollback(ConnUtils.java:233)
	at com.propn.golf.dao.trans.Trans.call(Trans.java:92)
	at com.propn.golf.dao.trans.TransTest$1.call(TransTest.java:30)
	at com.propn.golf.dao.trans.Trans.call(Trans.java:64)
	at com.propn.golf.dao.trans.Trans.call(Trans.java:31)
	at com.propn.golf.dao.trans.TransTest.main(TransTest.java:19)
11-21 23:28:31 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-169]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1389)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1364)
	at org.h2.jdbc.JdbcDatabaseMetaData.checkClosed(JdbcDatabaseMetaData.java:2781)
	at org.h2.jdbc.JdbcDatabaseMetaData.getTables(JdbcDatabaseMetaData.java:135)
	at com.jolbox.bonecp.BoneCP.isConnectionHandleAlive(BoneCP.java:677)
	at com.jolbox.bonecp.BoneCP.internalReleaseConnection(BoneCP.java:620)
	at com.jolbox.bonecp.ConnectionReleaseHelperThread.run(ConnectionReleaseHelperThread.java:77)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:662)
11-21 23:29:15 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Savepoint is invalid: "SYSTEM_SAVEPOINT_0"; SQL statement:
ROLLBACK TO SAVEPOINT SYSTEM_SAVEPOINT_0 [90063-169]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.engine.Session.rollbackToSavepoint(Session.java:769)
	at org.h2.command.dml.TransactionCommand.update(TransactionCommand.java:59)
	at org.h2.command.CommandContainer.update(CommandContainer.java:75)
	at org.h2.command.Command.executeUpdate(Command.java:230)
	at org.h2.jdbc.JdbcSavepoint.rollback(JdbcSavepoint.java:66)
	at org.h2.jdbc.JdbcConnection.rollback(JdbcConnection.java:966)
	at com.jolbox.bonecp.ConnectionHandle.rollback(ConnectionHandle.java:1054)
	at com.propn.golf.dao.trans.ConnUtils.rollback(ConnUtils.java:233)
	at com.propn.golf.dao.trans.Trans.call(Trans.java:92)
	at com.propn.golf.dao.trans.TransTest$1.call(TransTest.java:30)
	at com.propn.golf.dao.trans.Trans.call(Trans.java:64)
	at com.propn.golf.dao.trans.Trans.call(Trans.java:31)
	at com.propn.golf.dao.trans.TransTest.main(TransTest.java:19)
11-21 23:29:15 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-169]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1389)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1364)
	at org.h2.jdbc.JdbcDatabaseMetaData.checkClosed(JdbcDatabaseMetaData.java:2781)
	at org.h2.jdbc.JdbcDatabaseMetaData.getTables(JdbcDatabaseMetaData.java:135)
	at com.jolbox.bonecp.BoneCP.isConnectionHandleAlive(BoneCP.java:677)
	at com.jolbox.bonecp.BoneCP.internalReleaseConnection(BoneCP.java:620)
	at com.jolbox.bonecp.ConnectionReleaseHelperThread.run(ConnectionReleaseHelperThread.java:77)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:662)
11-21 23:30:12 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Savepoint is invalid: "SYSTEM_SAVEPOINT_0"; SQL statement:
ROLLBACK TO SAVEPOINT SYSTEM_SAVEPOINT_0 [90063-169]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.engine.Session.rollbackToSavepoint(Session.java:769)
	at org.h2.command.dml.TransactionCommand.update(TransactionCommand.java:59)
	at org.h2.command.CommandContainer.update(CommandContainer.java:75)
	at org.h2.command.Command.executeUpdate(Command.java:230)
	at org.h2.jdbc.JdbcSavepoint.rollback(JdbcSavepoint.java:66)
	at org.h2.jdbc.JdbcConnection.rollback(JdbcConnection.java:966)
	at com.jolbox.bonecp.ConnectionHandle.rollback(ConnectionHandle.java:1054)
	at com.propn.golf.dao.trans.ConnUtils.rollback(ConnUtils.java:233)
	at com.propn.golf.dao.trans.Trans.call(Trans.java:92)
	at com.propn.golf.dao.trans.TransTest$1.call(TransTest.java:30)
	at com.propn.golf.dao.trans.Trans.call(Trans.java:64)
	at com.propn.golf.dao.trans.Trans.call(Trans.java:31)
	at com.propn.golf.dao.trans.TransTest.main(TransTest.java:19)
11-21 23:30:12 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-169]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1389)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1364)
	at org.h2.jdbc.JdbcDatabaseMetaData.checkClosed(JdbcDatabaseMetaData.java:2781)
	at org.h2.jdbc.JdbcDatabaseMetaData.getTables(JdbcDatabaseMetaData.java:135)
	at com.jolbox.bonecp.BoneCP.isConnectionHandleAlive(BoneCP.java:677)
	at com.jolbox.bonecp.BoneCP.internalReleaseConnection(BoneCP.java:620)
	at com.jolbox.bonecp.ConnectionReleaseHelperThread.run(ConnectionReleaseHelperThread.java:77)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:662)
11-21 23:33:12 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Savepoint is invalid: "SYSTEM_SAVEPOINT_0"; SQL statement:
ROLLBACK TO SAVEPOINT SYSTEM_SAVEPOINT_0 [90063-169]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.engine.Session.rollbackToSavepoint(Session.java:769)
	at org.h2.command.dml.TransactionCommand.update(TransactionCommand.java:59)
	at org.h2.command.CommandContainer.update(CommandContainer.java:75)
	at org.h2.command.Command.executeUpdate(Command.java:230)
	at org.h2.jdbc.JdbcSavepoint.rollback(JdbcSavepoint.java:66)
	at org.h2.jdbc.JdbcConnection.rollback(JdbcConnection.java:966)
	at com.jolbox.bonecp.ConnectionHandle.rollback(ConnectionHandle.java:1054)
	at com.propn.golf.dao.trans.ConnUtils.rollback(ConnUtils.java:233)
	at com.propn.golf.dao.trans.Trans.call(Trans.java:92)
	at com.propn.golf.dao.trans.TransTest$1.call(TransTest.java:33)
	at com.propn.golf.dao.trans.Trans.call(Trans.java:64)
	at com.propn.golf.dao.trans.Trans.call(Trans.java:31)
	at com.propn.golf.dao.trans.TransTest.main(TransTest.java:19)
11-21 23:33:12 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-169]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1389)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1364)
	at org.h2.jdbc.JdbcDatabaseMetaData.checkClosed(JdbcDatabaseMetaData.java:2781)
	at org.h2.jdbc.JdbcDatabaseMetaData.getTables(JdbcDatabaseMetaData.java:135)
	at com.jolbox.bonecp.BoneCP.isConnectionHandleAlive(BoneCP.java:677)
	at com.jolbox.bonecp.BoneCP.internalReleaseConnection(BoneCP.java:620)
	at com.jolbox.bonecp.ConnectionReleaseHelperThread.run(ConnectionReleaseHelperThread.java:77)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:662)
11-21 23:34:52 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Savepoint is invalid: "SYSTEM_SAVEPOINT_0"; SQL statement:
ROLLBACK TO SAVEPOINT SYSTEM_SAVEPOINT_0 [90063-169]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.engine.Session.rollbackToSavepoint(Session.java:769)
	at org.h2.command.dml.TransactionCommand.update(TransactionCommand.java:59)
	at org.h2.command.CommandContainer.update(CommandContainer.java:75)
	at org.h2.command.Command.executeUpdate(Command.java:230)
	at org.h2.jdbc.JdbcSavepoint.rollback(JdbcSavepoint.java:66)
	at org.h2.jdbc.JdbcConnection.rollback(JdbcConnection.java:966)
	at com.jolbox.bonecp.ConnectionHandle.rollback(ConnectionHandle.java:1054)
	at com.propn.golf.dao.trans.ConnUtils.rollback(ConnUtils.java:233)
	at com.propn.golf.dao.trans.Trans.call(Trans.java:92)
	at com.propn.golf.dao.trans.TransTest$1.call(TransTest.java:33)
	at com.propn.golf.dao.trans.Trans.call(Trans.java:64)
	at com.propn.golf.dao.trans.Trans.call(Trans.java:31)
	at com.propn.golf.dao.trans.TransTest.main(TransTest.java:19)
11-21 23:34:52 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-169]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1389)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1364)
	at org.h2.jdbc.JdbcDatabaseMetaData.checkClosed(JdbcDatabaseMetaData.java:2781)
	at org.h2.jdbc.JdbcDatabaseMetaData.getTables(JdbcDatabaseMetaData.java:135)
	at com.jolbox.bonecp.BoneCP.isConnectionHandleAlive(BoneCP.java:677)
	at com.jolbox.bonecp.BoneCP.internalReleaseConnection(BoneCP.java:620)
	at com.jolbox.bonecp.ConnectionReleaseHelperThread.run(ConnectionReleaseHelperThread.java:77)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:662)
